### PR TITLE
Finding valac-0.x version

### PR DESCRIPTION
**Pull request by krokoziabla**
I guess there was two typos:

1. It should be VALAC_NAMES rather than VALAC_NAME
2. Both while statements search for 1.x version and it seems one of
   them was supposed to find 0.x one

### CODE REVIEW

**Comment by krokoziabla** [comment]
@nemequ would you give any feedback on this?

**Comment by nemequ** [comment]
Sorry.  Yeah, this seems completely reasonable, merged.

You're right, I think I was trying to plan ahead for 1.0 with one of those.

FWIW, I don't use this repo anymore; if you do I'd be happy to either add you as a collaborator or transfer it to you.  Last time I looked it was still pretty helpful so I'd hate to archive it, but obviously I can't be trusted to give it the timely maintenance it deserves…

**Comment by krokoziabla** [comment]
Are you sure you merged this? The most recent commit on master dates 2016 and the status of this PR is Closed, not Merged...

I think transferring the project to me will bury it into the ground because this page https://wiki.gnome.org/Projects/Vala/Tools references this repo and if it goes to me no one will ever no about this I guess. :-) So probably including me as a collaborator is a better option

**Comment by nemequ** [comment]
Hm, I clicked the merge on this issue button… Maybe I needed to to something else; I usually do everything from the command line, but I didn't want to bother checking this out.  Maybe I forgot to click the confirm button.  Anyways, it's merged now.

I've added you as a collaborator.  If you want me to transfer ownership just let me know; you can always update the link on the Wiki.

**Pull request merged**
